export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_MOVIE_PROCESS = "GET_LIST_MOVIE_PROCESS";
export const GET_LIST_MOVIE_ERROR = "GET_LIST_MOVIE_ERROR";

export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_DETAIL_PROCESS = "GET_MOVIE_DETAIL_PROCESS";
export const GET_MOVIE_DETAIL_ERROR = "GET_MOVIE_DETAIL_ERROR";
